---

- name: packages dependencies
  apt: >
    name={{ item }}
    state=present
  with_items:
    - libfontconfig1
  sudo: yes

- name: packages
  npm: >
    name={{ item }}
    state=present
    global=yes
  with_items:
    - phantomjs
  sudo: yes
