---

- name: packages dependencies
  apt: >
    pkg={{ item }}
    state=present
  with_items:
    - libfontconfig1
  sudo: yes

- name: packages
  npm: >
    name={{ item }}
    state=present
    global=yes
    version={{ version }}
  with_items:
    - phantomjs
  sudo: yes
